import { type NextPage } from "next";

import Head from "next/head";
import { SignInButton, SignOutButton, useUser } from "@clerk/nextjs";

const Home: NextPage = () => {
  const user = useUser();

  return (
    <>
      <Head>
        <title>Nilo App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-slate-600">
        {user.isSignedIn ? <SignOutButton /> : <SignInButton />}
      </main>
    </>
  );
};

export default Home;
