import Head from "next/head";

import { SignOutButton } from "@clerk/nextjs";

export default function Home() {
  return (
    <>
      <Head>
        <title>Nilo App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-slate-600">
        <SignOutButton />
      </main>
    </>
  );
}
